import React, { FC } from "react";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { HeaderLayout } from "@/components/HeaderLayout";

interface RootLayoutParams {
  params: {
    locale: string;
  };
  children: React.ReactNode;
}

const manrope = Manrope({ subsets: ["latin"] });

const locales = ["ru", "kk", "en"];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutParams> = ({ children, params }) => {
  const { locale } = params;

  if (!locales.includes(locale)) notFound();

  return (
    <html lang={locale}>
      <NextIntlClientProvider>
        <body className={manrope.className}>
          <HeaderLayout />
          <main className="main">{children}</main>
        </body>
      </NextIntlClientProvider>
    </html>
  );
};

export default RootLayout;
